development:
  # Register in sandbox veritrans and get your keys here:
  # https://my.sandbox.veritrans.co.id/settings/config_info
  client_key: <%= ENV["VT_DEV_CLIENT_KEY"] %>
  server_key: <%= ENV["VT_DEV_SERVER_KEY"] %>
  api_host: https://api.sandbox.veritrans.co.id

production:
  # Register and get your keys here:
  # https://my.veritrans.co.id/settings/config_info
  client_key: <%= ENV["VT_PROD_CLIENT_KEY"] %>
  server_key: <%= ENV["VT_PROD_SERVER_KEY"] %>
  api_host: https://api.veritrans.co.id